LOCAL_DATASET_PATH = "datasets"
HIVE_TARGET_DATASET = "target"
YARN_CONF_FILE = "/etc/hadoop/conf/yarn-site.xml"
HDFS_CONF_FILE = "/etc/hadoop/conf/hdfs-site.xml"
OOZIE_CONF_FILE = "/etc/oozie/conf/oozie-site.xml"
OOZIE_DIR_LIST = ["/oozie_data","/oozie_data/app_directory"]
OOZIE_APP_DIRECTORY = "/oozie_data/app_directory"
WORKFLOW_PATH = "src/workflow.xml"
QUERY_PATH = "src/hive.sql"
JOB_FILE_PATH = "src/job.properties"
OOZIE_INTERVAL = 20
URL_LIST = ['http://download.cms.gov/openpayments/PGYR13_P011819.ZIP', 'http://download.cms.gov/openpayments/PGYR14_P011819.ZIP', 'http://download.cms.gov/openpayments/PGYR15_P011819.ZIP', 'http://download.cms.gov/openpayments/PGYR16_P011819.ZIP', 'http://download.cms.gov/openpayments/PGYR17_P011819.ZIP' ]
SPARK2_HOME ="/usr/hdp/2.6.4.0-91/spark2/bin"
SCHEMA_PATH_ONE = "/spark_job_data/src/rpay/schema1"
SCHEMA_PATH_TWO = "/spark_job_data/src/rpay/schema2"
SPARK_OUTPUT_PATH = "/spark_job_data/out/rpay"
SPARK_DIR_LIST = ['/spark_job_data', '/spark_job_data/src', '/spark_job_data/src/rpay', '/spark_job_data/src/rpay/schema1', '/spark_job_data/src/rpay/schema2', '/spark_job_data/out', '/spark_job_data/out/rpay', '/user', '/user/root']
SPARK_INTERVAL = 10
CREATE_PARQUET_SCRIPT = "src/create_parq_common.py"
SPARK_QUERY_SCRIPT = "src/query.py"
HIVE_DIR_LIST = [ '/hive_job_data','/hive_job_data/rsrch_data','/hive_job_data/rsrch_data/2017','/hive_job_data/rsrch_data/2016', '/hive_job_data/rsrch_data/2015', '/hive_job_data/rsrch_data/2014', '/hive_job_data/rsrch_data/2013']
HIVE_TARGET = "target"
HDFS_TARGET = "/hive_job_data/rsrch_data"
